# Generated by Django 4.2.6 on 2023-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('nesting', models.CharField(max_length=100)),
                ('behavior', models.TextField(max_length=250)),
            ],
        ),
    ]
