# Generated by Django 4.2.6 on 2023-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(default='blank', max_length=300),
            preserve_default=False,
        ),
    ]
